# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: RustGenesGame.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0

    - name: Download and install Boost
      # You may pin to the exact commit or the version.
      # uses: MarkusJx/install-boost@3039450bb3dd2e8630d1cf10ec39cb1da3054bbd
      uses: MarkusJx/install-boost@v2.4.4
      with:
        # The boost version to install, e.g. "1.73.0"
        boost_version: 1.78.0
        # The toolset used to compile boost, e.g. "msvc"
        toolset: mingw
        # The platform version boost was compiled on, e.g. "18.04"
        platform_version: 2022
        # Whether the boost libraries are linked statically or dynamically
        link: shared
        # The architecture the binaries were built for
        arch: x86
        # The dirctory to install boost into
        boost_install_dir: ${{github.workspace}}
        # Wheter to use actions/cache to improve build times
        cache: true

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /m
      env:
        Boost_INCLUDE_DIR: ${{github.workspace}}/boost/include
        Boost_LIBRARY_DIR: ${{github.workspace}}/boost/lib
        Boost_LIBRARY: boost_archive
        
